var map_config = {
	'default':{
		'borderColor':'#cecece', //region outlines
		'mapShadow':'#000', //shadow color below the map
		'shadowOpacity':'0', //shadow opacity, value, 0-100
	},
	'map_1':{
		'hover': "<h3>ANDHRA PRADESH</h3><br>SVEP",  //region hover content
		'url':'http://keralanro.org/index.php/states-andra-projects', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':'#8e278f', //region color when page loads
		'overColor':'#ee007c', //region color when mouse hover
		'downColor':'#993366',//region color when mouse clicking
		'enable':true,//true/false to enable/disable this region
	},
	'map_2':{
		'hover': 'ARUNACHAL PRADESH',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_3':{
		'hover': '<h3>ASSAM</h3><br>PRI-CBO Convergence',
		'url':'http://keralanro.org/index.php/states-assam-projects',
		'target':'same_window',
		'upColor':'#2873B9',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_4':{
		'hover': '<h3>BIHAR</h3><br>MEC Project<br>SVEP',
		'url':'http://keralanro.org/index.php/states-bihar-projects',
		'target':'same_window',
		'upColor':'#E274AA',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_5':{
		'hover': '<h3>CHHATTISGARH</h3><br>PRI-CBO Convergence<br>SVEP',
		'url':'http://keralanro.org/index.php/states-chhattisgarh-projects',
		'target':'same_window',
		'upColor':'#979898',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_6':{
		'hover': '<h3>GOA</h3><br>Special Project',
		'url':'http://keralanro.org/index.php/states-goa-projects',
		'target':'same_window',
		'upColor':'#0A8F3E',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_7':{
		'hover': '<h3>GUJARAT</h3><br>MEC Project',
		'url':'http://keralanro.org/index.php/states-gujarath-projects',
		'target':'same_window',
		'upColor':'#be1d2c',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_8':{
		'hover': 'HARYANA',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_9':{
		'hover': 'HIMACHAL PRADESH',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_10':{
		'hover': 'JAMMU AND KASHMIR',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_11':{
		'hover': '<h3>JHARKHAND</h3><br>PRI-CBO Convergence<br>MEC Project<br>SVEP',
		'url':'http://keralanro.org/index.php/states-jhakhand-projects',
		'target':'same_window',
		'upColor':'#2e3092',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_12':{
		'hover': '<h3>KARNATAKA</h3><br>PRI-CBO Convergence<br>MEC Project',
		'url':'http://keralanro.org/index.php/states-karnataka-projects',
		'target':'same_window',
		'upColor':'#f7931d',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_13':{
		'hover': '<h3>KERALA</h3><br>SVEP',
		'url':'http://keralanro.org/index.php/states-kerala-projects',
		'target':'same_window',
		'upColor':'#8e278f',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_14':{
		'hover': '<h3>MADHYA PRADESH</h3><br>SVEP',
		'url':'http://keralanro.org/index.php/states-madhyapradesh-projects',
		'target':'same_window',
		'upColor':'#8e278f',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_15':{
		'hover': '<h3>MAHARASHTRA</h3><br>MEC Project<br>PRI-CBO Converegence',
		'url':'http://keralanro.org/index.php/states-maharasthra-projects',
		'target':'same_window',
		'upColor':'#f7931d',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_16':{
		'hover': '<h3>MANIPUR</h3><br>PRI-CBO Convergence',
		'url':'http://keralanro.org/index.php/states-manipur-projects',
		'target':'same_window',
		'upColor':'#2873B9',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_17':{
		'hover': 'MEGHALAYA',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_18':{
		'hover': 'MIZORAM',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_19':{
		'hover': 'NAGALAND',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_20':{
		'hover': '<h3>ODISHA</h3><br>PRI-CBO Convergence',
		'url':'http://keralanro.org/index.php/states-odisha-projects',
		'target':'same_window',
		'upColor':'#2873B9',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_21':{
		'hover': 'PUNJAB',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_22':{
		'hover': "<h3>RAJASTHAN</h3><br>PRI-CBO Convergence<br>MEC Project<br>SVEP",
		'url':'http://keralanro.org/index.php/states-rajasthan-projects',
		'target':'same_window',
		'upColor':'#2e3092',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_23':{
		'hover': '<h3>SIKKIM</h3><br>Special Project',
		'url':'http://keralanro.org/index.php/states-sikkim-projects',
		'target':'same_window',
		'upColor':'#0A8F3E',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_24':{
		'hover': 'TAMIL NADU',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_25':{
		'hover': 'TELANGANA',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_26':{
		'hover': '<h3>TRIPURA</h3><br>PRI-CBO Convergence',
		'url':'http://keralanro.org/index.php/tripura-convergence',
		'target':'same_window',
		'upColor':'#2873B9',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_27':{
		'hover': '<h3>UTTAR PRADESH</h3><br>SVEP',
		'url':'http://keralanro.org/index.php/states-uttarpradesh-projects',
		'target':'same_window',
		'upColor':'#8e278f',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_28':{
		'hover': 'UTTARAKHAND',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_29':{
		'hover': 'WEST BENGAL',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_30':{
		'hover': 'ANDAMAN AND NICOBAR ISLANDS',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_31':{
		'hover': 'CHANDIGARH',
		'url':'http://keralanro.org/index.php/states-chhattisgarh-projects',
		'target':'same_window',
		'upColor':'#000000',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_32':{
		'hover': 'DADRA AND NAGAR HAVELI',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_33':{
		'hover': 'DAMAN AND DIU',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_34':{
		'hover': '<h3>LAKSHADWEEP</h3><br>Special Project',
		'url':'http://keralanro.org/index.php/states-lakshadweep-projects',
		'target':'same_window',
		'upColor':'#0a8f3e',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':true,
	},
	'map_35':{
		'hover': 'NATIONAL CAPITAL TERRITORY OF DELHI',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	},
	'map_36':{
		'hover': 'PUDUCHERRY',
		'url':'http://www.keralanro.org/states/',
		'target':'same_window',
		'upColor':'#EBECED',
		'overColor':'#ee007c',
		'downColor':'#993366',
		'enable':false,
	}
}
